# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\"\xa0\x02\n\x03Imu\x12\x15\n\rorientation_x\x18\x01 \x01(\x02\x12\x15\n\rorientation_y\x18\x02 \x01(\x02\x12\x15\n\rorientation_z\x18\x03 \x01(\x02\x12\x15\n\rorientation_w\x18\x04 \x01(\x02\x12\x1a\n\x12\x61ngular_velocity_x\x18\x05 \x01(\x02\x12\x1a\n\x12\x61ngular_velocity_y\x18\x06 \x01(\x02\x12\x1a\n\x12\x61ngular_velocity_z\x18\x07 \x01(\x02\x12\x1d\n\x15linear_acceleration_x\x18\x08 \x01(\x02\x12\x1d\n\x15linear_acceleration_y\x18\t \x01(\x02\x12\x1d\n\x15linear_acceleration_z\x18\n \x01(\x02\x12\x0c\n\x04name\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMU']._serialized_start=14
  _globals['_IMU']._serialized_end=302
# @@protoc_insertion_point(module_scope)
