# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jointstate.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'jointstate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10jointstate.proto\"\x1b\n\nFloatArray\x12\r\n\x05value\x18\x01 \x03(\x02\"\xd6\x02\n\nJointState\x12\x0f\n\x07linkPos\x18\x01 \x03(\x02\x12\x0e\n\x06motPos\x18\x02 \x03(\x02\x12\x0f\n\x07linkVel\x18\x03 \x03(\x02\x12\x0e\n\x06motVel\x18\x04 \x03(\x02\x12\x0b\n\x03tor\x18\x05 \x03(\x02\x12\x11\n\tmotorTemp\x18\x06 \x03(\x02\x12\x12\n\ndriverTemp\x18\x07 \x03(\x02\x12\x0e\n\x06posRef\x18\x08 \x03(\x02\x12\x0e\n\x06velRef\x18\t \x03(\x02\x12\x0e\n\x06torRef\x18\n \x03(\x02\x12\t\n\x01k\x18\x0b \x03(\x02\x12\t\n\x01\x64\x18\x0c \x03(\x02\x12!\n\x03\x61ux\x18\r \x03(\x0b\x32\x14.JointState.AuxEntry\x12\r\n\x05vbatt\x18\x0e \x01(\x02\x12\r\n\x05ibatt\x18\x0f \x01(\x02\x12\x12\n\njointNames\x18\x10 \x03(\t\x1a\x37\n\x08\x41uxEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.FloatArray:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jointstate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTSTATE_AUXENTRY']._loaded_options = None
  _globals['_JOINTSTATE_AUXENTRY']._serialized_options = b'8\001'
  _globals['_FLOATARRAY']._serialized_start=20
  _globals['_FLOATARRAY']._serialized_end=47
  _globals['_JOINTSTATE']._serialized_start=50
  _globals['_JOINTSTATE']._serialized_end=392
  _globals['_JOINTSTATE_AUXENTRY']._serialized_start=337
  _globals['_JOINTSTATE_AUXENTRY']._serialized_end=392
# @@protoc_insertion_point(module_scope)
