# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joy_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rjoy_msg.proto\"C\n\x06JoyMsg\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\r\n\x05stamp\x18\x02 \x01(\x03\x12\x0c\n\x04\x61xes\x18\x03 \x03(\x02\x12\x0f\n\x07\x62uttons\x18\x04 \x03(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'joy_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOYMSG._serialized_start=17
  _JOYMSG._serialized_end=84
# @@protoc_insertion_point(module_scope)
