x-default-isaac-lab-template-environment: &default-isaac-lab-template-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - DISPLAY
  - XAUTHORITY=/root/.Xauthority
  - ACCEPT_EULA=Y

x-default-isaac-lab-template-deploy: &default-isaac-lab-template-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  kyon-isaac-base:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: kyon-isaac-base
    volumes:
      - $XAUTHORITY:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: ../
        target: /workspace/kyon_isaac
    network_mode: host
    environment: *default-isaac-lab-template-environment
    deploy: *default-isaac-lab-template-deploy
    # This is the entrypoint for the container
    stdin_open: true
    tty: true
    entrypoint: ''
    command: bash -ic 'pip install -e /workspace/kyon_isaac/source/kyon_isaac; bash -i'
